[tool.poetry]
name = "focus_cli"
version = "0.1.0"
description = "A CLI tool for focus protection"
authors = ["Your Name <your.email@example.com>"]
packages = [{include = "focus_cli"}]

[tool.poetry.dependencies]
python = ">=3.8,<3.14"
pyautogui = "^0.9.53"
keyboard = "^0.13.5"
tqdm = "^4.64.0"
click = "^8.1.3"
pyinstaller = "^6.10.0"
rich = "^13.7.1"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"

[tool.poetry.scripts]
focus = "focus_cli.cli:pomodoro"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"